# Generated by Django 4.2.4 on 2023-08-25 02:44

import convert.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("convert", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadimage",
            name="style",
            field=models.CharField(
                choices=[
                    ("Shinkai", "Shinkai"),
                    ("Hayao", "Hayao"),
                    ("Paprika", "Paprika"),
                    ("Hosoda", "Hosoda"),
                ],
                default="Shinkai",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="uploadimage",
            name="img",
            field=models.ImageField(upload_to=convert.models.update_filename),
        ),
        migrations.AlterField(
            model_name="uploadimage",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
