# Generated by Django 4.2.4 on 2023-08-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("convert", "0002_uploadimage_style_alter_uploadimage_img_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, null=True)),
                ("img_url", models.URLField()),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("Shinkai", "Shinkai"),
                            ("Hayao", "Hayao"),
                            ("Paprika", "Paprika"),
                            ("Hosoda", "Hosoda"),
                        ],
                        default="Shinkai",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
